import type { SandboxProvider, SecretStore } from "@ho/core";
import type { AttachmentStore } from "../attachments.ts";
import type { DaemonConfig } from "../config.ts";
import type { DirectoryPicker } from "../host-dialog.ts";
import type { IntakeService } from "../intake.ts";
import type { Logger } from "../logger.ts";
import type { OfficeGate } from "../office-gate.ts";
import type { Office } from "../office.ts";
import type { Resources } from "../paths.ts";
import type { RemoteCaller } from "../remote-peers.ts";
import type { RemoteService } from "../remote-service.ts";
import type { SessionManager } from "../sessions.ts";

export type RpcContext = {
  office: Office;
  sessions: SessionManager;
  attachments: AttachmentStore;
  gate: OfficeGate;
  intake: IntakeService;
  provider: SandboxProvider;
  secrets: SecretStore;
  config: DaemonConfig;
  home: string;
  resources: Resources;
  version: string;
  startedAt: string;
  gc: () => Promise<{ containers: string[]; volumes: string[]; images: string[] }>;
  pickDirectory: DirectoryPicker;
  remote: RemoteService;
  device?: RemoteCaller;
  log: Logger;
};
